# Generated by Django 4.2.3 on 2023-07-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_director_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Film',
        ),
    ]
